=== 8W9aG/jsbsim/JSBSimScript.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation><xs:documentation>
  This schema specifies the format that a JSBSim (www.jsbsim.org) must take to be
  valid. The JSBSim scripting language provides for specification of which aircraft
  and initialization file will be used for a "batch" run, as well as how long it will run,
  and at what time-step size it will be integrated at. Also, "Events" may be defined
  that can direct the simulation to set parameter values when specific conditions
  have been reached. The script author may also specify that some notifications
  should take place when an event is reached.
</xs:documentation>
</xs:annotation>

  <xs:element name="runscript">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="use"/>
        <xs:element ref="run" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="run">
    <xs:annotation>
      <xs:documentation>Contains the events.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element ref="event" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="start" type="xs:decimal" use="required"/>
      <xs:attribute name="end" type="xs:decimal" use="required"/>
      <xs:attribute name="dt" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="condition" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="set" maxOccurs="unbounded" minOccurs="0"/>
          <xs:element ref="notify" minOccurs="1" maxOccurs="1"/>
          <xs:element name="description" type="xs:string"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="optional"/>
      <xs:attribute name="persistent" use="optional">
        <xs:annotation><xs:documentation>
          [Documentation for persistent attribute.]
        </xs:documentation></xs:annotation>
        <xs:simpleType><xs:restriction base="xs:string"><xs:pattern value="true|false"/></xs:restriction></xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="condition">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="test" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="logic">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="AND|OR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="notify">
    <xs:annotation><xs:documentation>
      
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="property"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="property" type="xs:string"/>
  
  <xs:element name="set">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="action" type="xs:string" use="optional"/>
      <xs:attribute name="value" type="xs:decimal" use="required"/>
      <xs:attribute name="tc" type="xs:decimal" use="optional"/>
      <xs:attribute name="type" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="test">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="test"/>
      </xs:sequence>
      <xs:attribute name="logic" default="AND">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="AND|OR"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="description" type="xs:string">
    <xs:annotation id="test">
      <xs:documentation>Documents the runscript purpose.</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:element name="use">
    <xs:complexType>
      <xs:attribute name="aircraft" type="xs:string" use="required"/>
      <xs:attribute name="initialize" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== 8W9aG/jsbsim/scripts/c3104.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="C310-01A takeoff run">
    
  <description>For testing autopilot capability</description>
  <use aircraft="c310" initialize="reset00"/>
  
  <run start="0.0" end="300" dt="0.00833333">
  
    <event name="Set waypoints">
      <condition>sim-time-sec  eq  0.00</condition>
      <set name="ap/wp_latitude_rad" value="0.5236"/> <!-- 30 deg -->
      <set name="ap/wp_longitude_rad" value="1.3090"/> <!-- 75 deg -->
      <notify/>
    </event>
    
    <event name="Start engine">
      <condition>sim-time-sec  ge  0.25</condition>
      <set name="fcs/mixture-cmd-norm[0]" value="0.87"/>
      <set name="fcs/mixture-cmd-norm[1]" value="0.87"/>
      <set name="fcs/advance-cmd-norm[0]" value="1.0"/>
      <set name="fcs/advance-cmd-norm[1]" value="1.0"/>
      <set name="propulsion/magneto_cmd" value="3"/>
      <set name="fcs/throttle-cmd-norm[0]" value="1.0"/>
      <set name="fcs/throttle-cmd-norm[1]" value="1.0"/>
      <set name="propulsion/starter_cmd" value="1"/>
      <notify/>
    </event>
    
    <event name="Set attitude hold">
      <condition>position/h-agl-ft  ge  3.5</condition>
      <set name="ap/attitude_hold" value="1"/>
      <notify/>
    </event>

    <event name="Set heading hold">
      <condition>position/h-agl-ft  ge  30</condition>
      <set name="ap/attitude_hold" value="0"/>
      <set name="ap/heading_setpoint" value="300"/>
      <set name="ap/heading-setpoint-select" value="0"/>
      <set name="ap/heading_hold" value="1"/>
      <notify/>
    </event>
    
    <event name="Set altitude for 1,000 ft.">
      <condition>position/h-agl-ft  ge  10.0</condition>
      <set name="ap/altitude_setpoint" action="FG_EXP" value="1000.0" tc="10.0"/>
      <set name="ap/altitude_hold" value="1"/>
      <notify/>
    </event>
    
    <event name="Raise landing gear">
      <condition>position/h-agl-ft  ge  20</condition>
      <set name="gear/gear-cmd-norm" value="0"/>
      <notify/>
    </event>
    
    <event name="Set heading to 300 degrees and acquire/hold heading">
      <condition>position/h-agl-ft  ge  800</condition>
      <set name="ap/heading-setpoint-select" value="1"/>
      <notify/>
    </event>
    
    <event name="Set waypoints again">
      <condition>position/h-agl-ft  ge  800</condition>
      <delay> 50 </delay>
      <set name="ap/wp_latitude_rad" value="1.04712"/> <!-- 60 deg -->
      <set name="ap/wp_longitude_rad" value="1.3090"/> <!-- 75 deg -->
      <notify/>
    </event>
    
  </run>
</runscript>

=== 8W9aG/jsbsim/scripts/737_cruise_steady_turn.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="Cruise flight with steady turn in 737.">

  <description>
    This is a very simple script that trims the aircraft with running
    engines at altitude and runs out to 100 seconds. Some state data
    is printed out at ten second intervals. 
    
    There are two trimming algorithms that JSBSim uses:
    
    1) Classic trim
    2) Direct Search trim
    
    This script ONLY uses the classic trim method at this time.
  </description>

  <use aircraft="737" initialize="cruise_steady_turn_init"/> 

  <run start="0" end="100" dt="0.008333">

    <property value="0"> simulation/notify-time-trigger </property>

    <event name="Set engines running">
      <condition> sim-time-sec le 0.1 </condition>
      <set name="propulsion/engine[0]/set-running" value="1"/>
      <set name="propulsion/engine[1]/set-running" value="1"/>
      <notify/>
    </event>

    <!--
      For "do_simple_trim" (Classic trim):
      0: Longitudinal
      1: Full
      2: Ground
      3: Pullup
      4: Custom
      5: Turn
      6: None

      For "do_trim_analysis" (Direct Search trim):
      0: Longitudinal
      1: Full
      2: FullWingsLevel
      3: Turn
      4: Pullup
      5: TurnFull
      6: Ground
      7: Custom
      8: None
    -->
    
    <event name="Trim">
      <condition>
        sim-time-sec gt 0.1
      </condition>
      <set name="simulation/do_simple_trim" value="5"/>
      <!--<set name="simulation/do_trim_analysis" value="3"/>-->
      <delay>5.0</delay>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
        <property>velocities/vc-kts</property>
        <property>velocities/vc-fps</property>
        <property>velocities/vt-fps</property>
        <property>attitude/phi-rad</property>
        <property>attitude/theta-rad</property>
        <property>attitude/psi-rad</property>
      </notify>
    </event>

    <event name="Repeating Notify" persistent="true">
      <description>Output message at 5 second intervals</description>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
        <property>position/h-agl-ft</property>
        <property>velocities/vc-kts</property>
        <property>velocities/vc-fps</property>
        <property>velocities/vt-fps</property>
        <property>attitude/phi-rad</property>
        <property>attitude/theta-rad</property>
        <property>attitude/psi-rad</property>
      </notify>
      <condition> sim-time-sec >= simulation/notify-time-trigger </condition>
      <set name="simulation/notify-time-trigger" value="5" type="FG_DELTA"/>
    </event>

  </run>

</runscript>

=== 8W9aG/jsbsim/scripts/737_cruise.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="Cruise flight in 737.">

  <description>
    This is a very simple script that trims the aircraft with running
    engines at altitude and runs out to 100 seconds. Some state data
    is printed out at ten second intervals. 
    
    There are two trimming algorithms that JSBSim uses:
    
    1) Classic trim
    2) Direct Search trim
    
    For more information on the Direct Search trim, see, "A General
    Solution to the Aircraft Trim Problem", by Agostino De Marco,
    Eugene L. Duke, and Jon Berndt, AIAA 2007-6703.
    
    Both of these trim algorithms could theoretically be invoked
    at the same time, but normally only one or the other will be
    used at a time. In the script below, the engines are set running
    and then the trim task is commanded by setting the selected
    trim algorithm to "1".
  </description>

  <use aircraft="737" initialize="cruise_init"/>

  <run start="0" end="100" dt="0.008333">

    <property value="0"> simulation/notify-time-trigger </property>

    <event name="Set engines running">
      <condition> sim-time-sec le 0.1 </condition>
      <set name="propulsion/engine[0]/set-running" value="1"/>
      <set name="propulsion/engine[1]/set-running" value="1"/>
      <notify/>
    </event>

    <!--
      For "do_simple_trim" (Classic trim):
      0: Longitudinal
      1: Full
      2: Ground
      3: Pullup
      4: Custom
      5: Turn
      6: None
      
      For "do_trim_analysis" (Direct Search trim):
      0: Longitudinal
      1: Full
      2: FullWingsLevel
      3: Turn
      4: Pullup
      5: TurnFull
      6: Ground
      7: Custom
      8: None
      
    -->
    
    <event name="Trim">
      <condition> sim-time-sec gt 0.1 </condition>
<!--      <set name="simulation/do_simple_trim" value="0"/> -->
      <set name="simulation/do_trim_analysis" value="1"/>
      <delay>5.0</delay>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
        <property>velocities/vc-kts</property>
        <property>velocities/vc-fps</property>
        <property>velocities/vt-fps</property>
      </notify>
    </event>

    <event name="Repeating Notify" persistent="true">
      <description>Output message at 5 second intervals</description>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
        <property>position/h-agl-ft</property>
        <property>velocities/vc-kts</property>
        <property>velocities/vc-fps</property>
        <property>velocities/vt-fps</property>
      </notify>
      <condition> sim-time-sec >= simulation/notify-time-trigger </condition>
      <set name="simulation/notify-time-trigger" value="5" type="FG_DELTA"/>
    </event>

  </run>

</runscript>

=== 8W9aG/jsbsim/scripts/f16_runway_test.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="F-16 aircraft runway test">
  <description>This run is for testing an F-16 just sitting on the runway</description>
  <use aircraft="f16" initialize="reset00"/>
  <run start="0.0" end="45" dt="0.00833333">

    <event name="15-second control surface setting">
      <condition> sim-time-sec >= 15.00 </condition>
      <set name="fcs/elevator-cmd-norm" value="0.2"/>
      <set name="fcs/aileron-cmd-norm" value="0.2"/>
      <notify/>
    </event>

    <event name="30-second control surface setting">
      <condition> sim-time-sec >= 30.00 </condition>
      <set name="fcs/elevator-cmd-norm" value="0.0"/>
      <set name="fcs/aileron-cmd-norm" value="0.0"/>
      <notify/>
    </event>

  </run>
</runscript>

=== 8W9aG/jsbsim/scripts/ov10_runway.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://www.jsbsim.org/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.jsbsim.org/JSBSimScript.xsd"
    name="OV-10 runway test">
  <description>For testing OV-10 ground reactions</description>
  <use aircraft="ov10" initialize="reset00"/>
  <run start="0.0" end="100" dt="0.00833333">

    <event name="On-ground trim">
      <description>The aircraft is trimmed on-ground.</description>
      <condition>sim-time-sec ge 0.25</condition>
      <set name="simulation/do_trim" value="2"/> <!-- on-ground trim -->
      <notify/>
    </event>

    <event name="Start engine: Starter">
      <description>The starter for both engines is turned on.</description>
      <condition>sim-time-sec ge 10.0</condition>
      <set name="propulsion/starter_cmd" value="1"/>
      <notify/>
    </event>

    <event name="Start engine: Cutoff">
      <description>Cutoff is turned off, allowing fuel to flow.</description>
      <condition>propulsion/engine[0]/n2 ge 15.0</condition>
      <set name="propulsion/cutoff_cmd" value="0"/>
      <set name="fcs/throttle-cmd-norm[0]" value="0.4"/>
      <set name="fcs/throttle-cmd-norm[1]" value="0.4"/>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/starter_cmd</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
      </notify>
    </event>

    <event name="Throttle-up">
      <description>Move throttle to full for take-off.</description>
      <condition>propulsion/engine[0]/n2 ge 15.0</condition>
      <delay>5.0</delay>
      <set name="fcs/throttle-cmd-norm[0]" value="1.0"/>
      <set name="fcs/throttle-cmd-norm[1]" value="1.0"/>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
        <property>velocities/vc-kts</property>
      </notify>
    </event>

    <event name="Notify Velocity">
      <description>Notify when velocity goes above 10 kts.</description>
      <condition>velocities/vc-kts ge 10.0</condition>
      <notify>
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust</property>
        <property>propulsion/engine[1]/thrust</property>
        <property>velocities/vc-kts</property>
      </notify>
    </event>

  </run>

</runscript>
